### ISSUE TITLE
Become a project 100% Healthy 

### ISSUE THREAD

**Issue by lipemorais** [datasciencebr/serenata-toolbox#77]
The purpose of this PR is have 100% of Health, fixing all coding quality analyze issues. 
[landscape build](https://landscape.io/github/datasciencebr/serenata-toolbox/147)

**Comment by othman853** [comment]
I just saw that Landscape is in a hiatus for Open Source projects, meaning that they may not work for a while: https://landscape.io/hiatus

**Comment by cuducos** [comment]
~meaning that they may not work for a long while~

Nope. Meaning that CI is disabled for a while. We have to trigger it manually instead.

**Comment by lipemorais** [comment]
I ran prospector using the configuration file below:
```
// .prospector.yaml
output-format: grouped

strictness: high
test-warnings: true
doc-warnings: false
member-warnings: true

pep8:
  full: true
  options:
    max-line-length: 250

mccabe:
  run: true
```

There is any additional configuration that would be good?
Should it be running on CI too? I think that will be good to keep the healthy of the project 100%.
